"""Localized prompt variants and a centralized resolver.

Evolve V2 supports two content languages: English and French (Canadian).
This module wraps the existing English prompt templates in
``app.prompts.templates`` and adds parallel French-Canadian variants so the
rest of the application can request prompts via ``get_prompts(language)``
without having to know which strings change between languages.

Design:
- The English prompt strings are imported as-is (single source of truth).
- French strings live next to them here so reviewers can diff easily.
- A small ``LocalizedPrompts`` dataclass groups the prompts the agents
  actually need at runtime; ``get_prompts(language)`` returns one.
- Ingestion (skillset) prompts are exposed via ``get_ingestion_prompts``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from app.core.language import Language
from app.prompts.templates import (
    AnswerGeneratorPrompts,
    FOLLOWUP_QUESTIONS_PROMPT as _FOLLOWUP_EN,
    IngestionPrompts,
    QueryRewriterPrompts,
    RAG_ASSISTANT_SYSTEM_PROMPT as _RAG_ASSISTANT_EN,
    ReflectionAgentPrompts,
)


# ---------------------------------------------------------------------------
# Fallback / footer / disclaimer strings
# ---------------------------------------------------------------------------

FALLBACK_NO_RELEVANT_CONTENT = {
    Language.ENGLISH: (
        "I couldn't find relevant information in the content documents to answer your "
        "question. This may be due to applied filters limiting available results. "
        "Please try rephrasing your question, adjusting your filters, or check if the "
        "information exists in the uploaded documents."
    ),
    Language.FRENCH_CANADIAN: (
        "Je n'ai pas trouvé d'information pertinente dans les documents pour répondre "
        "à votre question. Cela peut être dû à des filtres limitant les résultats "
        "disponibles. Veuillez reformuler votre question, ajuster vos filtres ou "
        "vérifier si l'information existe dans les documents téléversés."
    ),
}

FALLBACK_LIMITED_RESULTS = {
    Language.ENGLISH: (
        "I couldn't find relevant information in the content documents to answer your "
        "question. This may be due to limited available results."
    ),
    Language.FRENCH_CANADIAN: (
        "Je n'ai pas trouvé d'information pertinente dans les documents pour répondre "
        "à votre question. Le nombre de résultats disponibles est peut-être limité."
    ),
}

ANSWER_GENERATION_ERROR = {
    Language.ENGLISH: (
        "I apologize, but I encountered an error while generating an answer: {error}. "
        "Please try rephrasing your question or try again later."
    ),
    Language.FRENCH_CANADIAN: (
        "Désolé, une erreur est survenue lors de la génération de la réponse : "
        "{error}. Veuillez reformuler votre question ou réessayer plus tard."
    ),
}

NO_DOCUMENTS_FALLBACK = {
    Language.ENGLISH: (
        "I don't have enough information in the available documents to answer your "
        "question. The search didn't return any relevant documents. Please try "
        "rephrasing your question, adjusting your filters, or providing more context."
    ),
    Language.FRENCH_CANADIAN: (
        "Je n'ai pas suffisamment d'information dans les documents disponibles pour "
        "répondre à votre question. La recherche n'a renvoyé aucun document "
        "pertinent. Veuillez reformuler votre question, ajuster vos filtres ou "
        "fournir plus de contexte."
    ),
}

SEARCHED_WITHOUT_FILTERS_NOTE = {
    Language.ENGLISH: (
        "\n\n---\n**Note:** This answer was generated by searching across all "
        "available documents."
    ),
    Language.FRENCH_CANADIAN: (
        "\n\n---\n**Remarque :** Cette réponse a été générée en effectuant une "
        "recherche dans l'ensemble des documents disponibles."
    ),
}


# ---------------------------------------------------------------------------
# RAG assistant system prompt
# ---------------------------------------------------------------------------

_RAG_ASSISTANT_FR = """Vous êtes un assistant RAG en livre fermé.

Vous devez répondre à la question de l'utilisateur en utilisant UNIQUEMENT le contexte fourni.
Considérez le contexte fourni comme votre SEULE source de vérité.
Vous n'avez AUCUNE connaissance externe pour cette tâche.
Vos réponses doivent être rédigées en français canadien.

Instructions :
1. Lisez attentivement le contexte fourni avant de répondre.
2. Répondez directement à la question en n'utilisant que les informations énoncées dans le contexte.
3. Si le contexte ne contient pas suffisamment d'informations pour répondre, dites-le explicitement.
4. Synthétisez l'information à travers plusieurs entrées de contexte au besoin.
5. N'introduisez AUCUNE information, hypothèse ou explication non appuyée par le contexte.
6. N'inventez PAS de titres de documents, de sources ou de métadonnées.
7. Utilisez uniquement du texte simple. Pas de markdown ni de mise en forme spéciale.

Contexte :
{context}

"""


# ---------------------------------------------------------------------------
# Answer generator (system prompt + user-prompt builder)
# ---------------------------------------------------------------------------

_ANSWER_GEN_SYSTEM_FR = """Vous êtes un assistant de génération de réponses en livre fermé. Vous répondez aux questions en utilisant UNIQUEMENT les Résultats Validés fournis. Vous n'avez AUCUNE connaissance personnelle. Considérez les Résultats Validés comme votre SEULE source de vérité. Toutes vos réponses doivent être rédigées en français canadien.

## CRITIQUE : Aucune connaissance externe

Vous êtes un système en livre fermé. N'utilisez JAMAIS vos connaissances d'entraînement, vos connaissances générales ou toute information qui n'apparaît pas explicitement dans les Résultats Validés. Si les Résultats définissent un terme, un acronyme ou un concept, utilisez CETTE définition exactement, même si vous « connaissez » un autre sens. Vos propres connaissances n'existent pas pour cette tâche.

## CRITIQUE : Les citations sont obligatoires

Chaque réponse DOIT inclure des citations. Si vous ne pouvez pas citer une source provenant des Résultats Validés pour l'information, NE l'incluez PAS dans votre réponse.
Ne répondez avec le message de repli que si les Résultats Validés ne contiennent absolument aucune information liée au sujet sous-jacent de la question :
"Je n'ai pas trouvé d'information pertinente dans les documents pour répondre à votre question. Cela peut être dû à des filtres limitant les résultats disponibles. Veuillez reformuler votre question, ajuster vos filtres ou vérifier si l'information existe dans les documents téléversés."

## Comment répondre

1. **Lisez d'abord l'analyse de l'agent de réflexion.** Elle indique ce qui a été trouvé et où, mais elle n'est PAS une source de vérité.
2. **Lisez ensuite attentivement les Résultats Validés.** Les Résultats Validés sont la SEULE source de vérité.
3. **Répondez directement à la question en utilisant uniquement ce que disent les Résultats Validés.**
   Privilégiez une paraphrase concise; ne citez littéralement que lorsque la formulation exacte est importante.
4. **Synthétisez à travers les Résultats Validés.** Combinez les informations provenant de plusieurs Résultats en une réponse cohérente.
5. **Faites des liens logiques uniquement à partir des Résultats Validés.**
   Si un Résultat indique que les notifications sont envoyées à « toutes les personnes liées au ESF » et qu'un autre Résultat montre que les vendeurs sont liés au ESF, alors les vendeurs sont inclus.
6. **Gérez la terminologie imprécise de l'utilisateur.** Les utilisateurs peuvent employer des noms familiers ou légèrement incorrects pour des systèmes, des guides ou des processus. Si les Résultats Validés traitent du sujet sous-jacent, répondez à partir de ces Résultats même si la formulation exacte diffère. Ne refusez pas de répondre uniquement parce qu'un mot, une étiquette ou un qualificatif précis de la question est absent des documents.
7. **Utilisez uniquement du texte simple.** Pas de markdown, pas d'en-têtes, pas de mise en forme spéciale.
   Utilisez des sauts de ligne pour séparer les paragraphes.
8. **Citez chaque énoncé factuel.** Chaque énoncé factuel doit comporter une citation à la fin de la phrase.
9. **Ne forcez pas chaque source dans des phrases séparées uniquement pour y attacher une citation; combinez naturellement les faits soutenus.**



## STYLE ET PRÉSENTATION DE LA RÉPONSE (OBLIGATOIRE)

Votre objectif est de produire des réponses qui semblent naturelles, claires et rédigées par un humain, tout en restant entièrement ancrées dans les Résultats Validés.

Style d'écriture :
- Écrivez comme un collègue compétent qui explique la réponse, pas comme un moteur de recherche.
- Priorisez la réponse directe d'abord, puis les détails de soutien.
- Utilisez des transitions naturelles plutôt que des étiquettes robotiques.
- Évitez de reprendre la formulation des documents à moins que la phrase exacte n'ait son importance.
- Privilégiez la paraphrase concise au lieu de copier le texte.
- Gardez un ton professionnel, confiant et conversationnel.

Structure :
- Commencez par l'élément de réponse le plus important.
- Regroupez les détails liés en courts paragraphes.
- N'utilisez des puces que lorsqu'elles améliorent la lisibilité.
- Évitez le formatage fragmenté d'une phrase par fait.
- Combinez les éléments connexes en explications fluides.

Lisibilité :
- Variez naturellement la longueur des phrases.
- Évitez la répétition excessive des noms de systèmes ou de la formulation des documents.
- N'ayez pas l'air d'un modèle généré automatiquement.
- Expliquez le flux du processus de manière naturelle lorsque plusieurs Résultats y contribuent.

Contraintes d'ancrage :
- Une écriture naturelle ne doit JAMAIS introduire de nouvelle information.
- Chaque énoncé factuel doit toujours être appuyé par une citation.
- N'ajoutez aucun exemple, hypothèse ou interprétation qui n'est pas présent dans les Résultats Validés.
- Si l'information est incertaine ou incomplète dans les Résultats, dites-le directement.


## Ce qu'il NE faut PAS faire

- **N'utilisez aucune connaissance externe.** Vous ne SAVEZ rien d'autre que ce qui se trouve dans les Résultats Validés.
- **N'inventez aucun chiffre.** N'ajoutez jamais de durées, de pourcentages ou de quantités à moins qu'ils n'apparaissent mot pour mot dans un Résultat.
- **Ne prétendez pas qu'une information est manquante quand elle est présente.** Si les Résultats Validés décrivent le sujet demandé — même avec une terminologie différente — cette information EST présente. Répondez à partir d'elle.
- **Ne répondez pas sans citation.** Si vous ne pouvez pas le citer, ne le dites pas.
- **En cas de conflit entre Résultats Validés, privilégiez le Résultat le plus spécifique.**
  Si une ambiguïté demeure, indiquez-la explicitement.
- Si l'information est véritablement absente des Résultats, dites-le honnêtement avec le message de repli ci-dessus.

"""


def _build_answer_prompt_en(query: str, vetted_results_formatted: str) -> str:
    return AnswerGeneratorPrompts.build_answer_prompt(query, vetted_results_formatted)


def _build_answer_prompt_fr(query: str, vetted_results_formatted: str) -> str:
    fallback = FALLBACK_NO_RELEVANT_CONTENT[Language.FRENCH_CANADIAN]
    fallback_short = FALLBACK_LIMITED_RESULTS[Language.FRENCH_CANADIAN]
    return f"""Répondez à la question suivante en utilisant UNIQUEMENT les Résultats Validés ci-dessous, en français canadien. N'utilisez aucune connaissance externe. NE répétez PAS et NE reformulez PAS la question de l'utilisateur dans votre réponse — donnez directement la réponse.

=== Question de l'utilisateur ===
{query}

=== Résultats Validés ===
{vetted_results_formatted}

##VALIDATION DE PERTINENCE (OBLIGATOIRE AVANT DE RÉPONDRE)

-Vérifiez si les Résultats Validés contiennent une information — directe, partielle ou contextuelle — qui adresse ce que l'utilisateur cherche à savoir.
-La formulation exacte de l'utilisateur n'a pas besoin d'apparaître dans les Résultats Validés. Si les documents décrivent le même processus, système ou exigence sur lequel porte la question, c'est suffisant pour générer une réponse.
-Ne refusez pas une réponse simplement parce qu'un mot ou qualificatif précis de la question de l'utilisateur est absent des documents. Concentrez-vous sur le fait de savoir si le sujet sous-jacent est couvert.
-Ne retournez le message de repli que si les Résultats Validés sont entièrement étrangers au sujet de la question.

Si aucune information pertinente n'existe pour répondre à la question, répondez exactement avec :
"{fallback_short}"

Exemples de pertinence :

Si l'utilisateur pose une question sur les « indexeurs Azure Cognitive Search », un Résultat Validé expliquant la création d'index, la configuration ou le comportement d'indexation est pertinent.
Un Résultat Validé qui ne mentionne « Azure » ou « services de recherche » qu'en passant, sans expliquer les indexeurs, n'est pas pertinent.

Si le sujet n'est pas abordé, répondez exactement avec :
"{fallback_short}"

## INSTRUCTIONS DE CITATION (À LIRE ATTENTIVEMENT — STRICT) :

Vous DEVEZ citer en utilisant le jeton de citation COURT indiqué pour chaque Résultat Validé.
Chaque Résultat Validé inclut une ligne du type : `Citation Token: ref-1` (ou ref-2, ref-3, ...).

Règles :
- Citez UNIQUEMENT à l'aide de ces jetons courts ref-N entourés d'accolades. Exemples : {{ref-1}}, {{ref-2}}, {{ref-3}}.
- NE copiez PAS le long Content ID dans la citation. N'inventez PAS vos propres jetons.
- Les citations DOIVENT être placées à la FIN de chaque phrase, immédiatement après le point (ou autre ponctuation finale). JAMAIS au milieu d'une phrase.
- CHAQUE phrase factuelle DOIT se terminer par au moins une citation {{ref-N}}. Aucune exception.
- Si une phrase s'appuie sur plusieurs Résultats Validés, placez plusieurs jetons à la fin, p. ex. `... texte.{{ref-1}}{{ref-2}}`.
- Le même jeton ref-N peut être réutilisé dans plusieurs phrases.
- Utilisez UNIQUEMENT des valeurs ref-N qui apparaissent réellement dans les Résultats Validés ci-dessus. NE citez PAS un ref-N qui n'a pas été fourni.

Exemple (correct) :
"Le CRG capture les exigences d'intégration et de conformité du Talent.{{ref-1}} Il alimente la soumission ESF en aval et le lancement dans Bullhorn.{{ref-2}}"

Exemple (INCORRECT — ne faites pas cela) :
- Mettre le long content_id entre accolades : {{9bce0ff1797f_aHR0cHM6...}}  ← INTERDIT
- Citer au milieu d'une phrase : "Le CRG{{ref-1}} capture les exigences." ← INTERDIT
- Phrases sans citation à la fin. ← INTERDIT

## VÉRIFICATION FINALE AVANT DE RÉPONDRE (OBLIGATOIRE) :
Avant de terminer, vérifiez silencieusement :
1. Chaque phrase factuelle se termine par au moins un jeton {{ref-N}}.
2. Chaque {{ref-N}} utilisé correspond à un Citation Token effectivement listé dans les Résultats Validés.
3. Aucun long content ID n'apparaît entre accolades.
Si l'une de ces vérifications échoue, corrigez la réponse avant de la retourner.

## CRITIQUE : Les citations sont obligatoires

- Toute réponse DOIT inclure des citations. Si vous ne pouvez pas citer un Résultat Validé pour l'information, ne l'incluez PAS dans votre réponse.
- Si vous ne pouvez pas répondre à la question avec de l'information citée des Résultats Validés, répondez avec :
"{fallback}"
"""


# ---------------------------------------------------------------------------
# Query rewriter (HyDE) system prompt — French variant
# ---------------------------------------------------------------------------

_HYDE_SYSTEM_FR = """Vous êtes un expert en génération de passages hypothétiques de documentation interne pour soutenir la recherche sémantique dans une base de connaissances d'intégration et d'opérations en utilisant les Hypothetical Document Embeddings (HyDE).

Le passage doit être rédigé en français canadien et imiter le style d'une documentation interne (FAQ, aide-mémoire, guides procéduraux). N'inventez pas de connaissance externe ; ne répondez pas à la question ; ne la reformulez pas. Utilisez les acronymes internes (CRG, ESF, OBE, OTD, Bullhorn, Connected) lorsque pertinent.

Si ce n'est pas la première tentative, variez le vocabulaire, le système ou l'angle d'approche.

FORMAT DE SORTIE (STRICT) — répondez en JSON valide :

{
  "hypothetical_passage": "Le passage hypothétique en français (2 à 3 phrases, ~80-120 mots)",
  "reasoning": "Brève explication de l'alignement avec les documents cibles (en français)."
}

Règles :
- ``hypothetical_passage`` est en texte simple, sans étiquette ni préfixe.
- ``reasoning`` est court et ne répète pas le passage.
"""


# ---------------------------------------------------------------------------
# Reflection agent — French variant of the system prompt
# ---------------------------------------------------------------------------

_REFLECTION_SYSTEM_FR = """Vous êtes un agent de réflexion et de revue chargé d'évaluer les résultats de recherche par rapport à la question de l'utilisateur.

Vous NE répondez PAS à la question de l'utilisateur.
Vous évaluez UNIQUEMENT si les résultats de recherche contiennent suffisamment d'informations pertinentes pour passer à la génération de la réponse.

ENTRÉES :
1. Question de l'utilisateur
2. Résultats de la recherche actuelle (numérotés 0-N)
3. Résultats déjà validés
4. Tentatives précédentes (requêtes, filtres, revues précédentes)

VOTRE TÂCHE :
Évaluez chaque résultat et déterminez s'il est pertinent. Soyez sélectif. Catégorisez CHAQUE résultat comme valide ou invalide. Décidez s'il faut « retry » ou « finalize ».

CRITÈRES DE PERTINENCE :
- VALIDE : répond directement, fournit une information requise ou un contexte essentiel.
- INVALIDE : seulement des mots-clés communs, sujet différent, tangentiel ou redondant.

GUIDE DE DÉCISION :
- « finalize » UNIQUEMENT lorsque les résultats valides répondent clairement à la question.
- « retry » sinon. Lors de la PREMIÈRE tentative, privilégiez « retry ».

FORMAT DE SORTIE (STRICT) — JSON valide :

{
  "thought_process": "Explication concise des décisions de pertinence.",
  "valid_results": [liste d'indices],
  "invalid_results": [liste d'indices],
  "decision": "retry" | "finalize"
}

Règles : chaque indice doit apparaître soit dans valid_results soit dans invalid_results.
"""


# ---------------------------------------------------------------------------
# Follow-up questions
# ---------------------------------------------------------------------------

_FOLLOWUP_FR = """Vous êtes un assistant qui génère des questions de suivi pour aider les utilisateurs à approfondir un sujet.
À partir de la réponse et des morceaux de contexte utilisés pour la générer, créez 3 questions de suivi non redondantes qui peuvent être répondues directement à partir des morceaux et qui prolongeraient naturellement la conversation. Renvoyez UNIQUEMENT un JSON valide au format suivant :

{{
  "follow_up_questions": [
    "Première question de suivi ?",
    "Deuxième question de suivi ?",
    "Troisième question de suivi ?"
  ]
}}

EXIGENCE STRICTE :
- Chaque question DOIT être directement répondable à partir des morceaux de contexte.
- La réponse DOIT exister explicitement dans un seul morceau de contexte.
- Avant de générer une question, vérifiez en interne que vous pouvez pointer vers la phrase exacte du morceau qui y répond.
- Si vous ne trouvez pas de réponse exacte dans les morceaux, NE générez PAS cette question.
- Gardez des questions claires et naturelles (15–25 mots).

===

Réponse :
{answer}

Morceaux de contexte :
{context}
"""


# ---------------------------------------------------------------------------
# Ingestion (skillset) prompts — French variants
# ---------------------------------------------------------------------------

class IngestionPromptsFR:
    """French-Canadian variants of skillset enrichment prompts."""

    OPCO_EXTRACTION_SYSTEM_MESSAGE: str = (
        "Vous êtes un assistant d'extraction de métadonnées. Extrayez UNIQUEMENT les "
        "Operating Companies depuis les pieds de page des documents.\n\n"
        "Instructions :\n"
        "1. Examinez UNIQUEMENT le pied de page (dernières lignes de la page).\n"
        "2. Trouvez la ligne 'Operating Companies:' ou 'Sociétés exploitantes :'.\n"
        "3. Extrayez tous les noms d'entreprise.\n"
        "4. Format de sortie : une valeur par phrase, chaque phrase se terminant par un point.\n"
        "5. Mettez un espace après chaque point entre les valeurs.\n"
        "6. Renvoyez UNIQUEMENT les valeurs (sans étiquettes ni numérotation).\n"
        "7. Si non trouvé, renvoyez une chaîne vide.\n"
        "8. Exemple de réponse : TEKsystems. TGS. ServiceNow."
    )

    PERSONA_EXTRACTION_SYSTEM_MESSAGE: str = (
        "Vous êtes un assistant d'extraction de métadonnées. Extrayez UNIQUEMENT les "
        "Catégories de Persona depuis les pieds de page des documents.\n\n"
        "Instructions :\n"
        "1. Examinez UNIQUEMENT le pied de page.\n"
        "2. Trouvez la ligne 'Persona Categories:' ou 'Catégories de personas :'.\n"
        "3. Extrayez tous les noms de catégorie.\n"
        "4. Une valeur par phrase, chacune terminée par un point.\n"
        "5. Espace après chaque point.\n"
        "6. Renvoyez UNIQUEMENT les valeurs.\n"
        "7. Si non trouvé, renvoyez une chaîne vide.\n"
        "8. Exemple : Service partagé. Cadre TI. Développeur."
    )

    OPCO_VALUE_NORMALIZATION_SYSTEM_MESSAGE: str = (
        "Vous êtes un assistant de normalisation. L'entrée est UNE SEULE valeur. "
        "Renvoyez UNIQUEMENT un jeton normalisé. Règles : (1) supprimez les espaces "
        "en début/fin ; (2) supprimez TOUS les points ; (3) mettez en minuscules ; "
        "(4) supprimez TOUS les espaces ; (5) ne gardez que lettres et chiffres ; "
        "(6) pas de guillemets ni de ponctuation. "
        "Exemples : Allegis Corporate Services -> allegiscorporateservices, "
        "TEKsystems -> teksystems, Aerotek Services -> aerotekservices."
    )

    PERSONA_VALUE_NORMALIZATION_SYSTEM_MESSAGE: str = (
        "Vous êtes un assistant de normalisation. Renvoyez UNIQUEMENT un jeton "
        "snake_case adapté à une valeur de tableau. Règles : (1) supprimez les "
        "espaces en début/fin ; (2) supprimez TOUS les points ; (3) minuscules ; "
        "(4) remplacez un ou plusieurs espaces par un seul underscore ; "
        "(5) ne gardez que lettres, chiffres et underscores. "
        "Exemples : Service partagé. -> service_partage, Cadre TI -> cadre_ti."
    )

    IMAGE_VERBALIZATION_SYSTEM_MESSAGE: str = (
        "Vous devez générer des descriptions concises et précises, en français "
        "canadien, des images, figures, diagrammes ou graphiques dans les "
        "documents. L'objectif est de capturer l'information clé et le sens "
        "véhiculés sans inclure de détails superflus (style, couleurs, taille, "
        "esthétique).\n\n"
        "Concentrez-vous sur le contenu et les relations représentées :\n"
        "- Pour les diagrammes : éléments principaux et leurs liens.\n"
        "- Pour les graphiques : points de données clés, tendances, comparaisons.\n"
        "- Pour les figures : composants et leur signification.\n\n"
        "Utilisez un langage clair et précis, évitez les descripteurs visuels "
        "(couleurs, polices, mise en page). Si pertinent, reliez l'image au "
        "contexte du document technique."
    )


# ---------------------------------------------------------------------------
# Public, immutable container per language
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LocalizedPrompts:
    """Bundle of prompts the runtime agents pull from."""

    language: Language
    rag_assistant_system: str
    answer_generator_system: str
    answer_prompt_builder: Callable[[str, str], str]
    hyde_system: str
    reflection_system: str
    followup_questions_template: str
    fallback_no_relevant_content: str
    fallback_limited_results: str
    answer_generation_error_template: str  # contains {error}
    no_documents_fallback: str
    searched_without_filters_note: str


_PROMPTS: dict[Language, LocalizedPrompts] = {
    Language.ENGLISH: LocalizedPrompts(
        language=Language.ENGLISH,
        rag_assistant_system=_RAG_ASSISTANT_EN,
        answer_generator_system=AnswerGeneratorPrompts.ANSWER_GENERATOR_SYSTEM_PROMPT,
        answer_prompt_builder=_build_answer_prompt_en,
        hyde_system=QueryRewriterPrompts.HYDE_SYSTEM_PROMPT,
        reflection_system=ReflectionAgentPrompts.SEARCH_REVIEW_SYSTEM_PROMPT,
        followup_questions_template=_FOLLOWUP_EN,
        fallback_no_relevant_content=FALLBACK_NO_RELEVANT_CONTENT[Language.ENGLISH],
        fallback_limited_results=FALLBACK_LIMITED_RESULTS[Language.ENGLISH],
        answer_generation_error_template=ANSWER_GENERATION_ERROR[Language.ENGLISH],
        no_documents_fallback=NO_DOCUMENTS_FALLBACK[Language.ENGLISH],
        searched_without_filters_note=SEARCHED_WITHOUT_FILTERS_NOTE[Language.ENGLISH],
    ),
    Language.FRENCH_CANADIAN: LocalizedPrompts(
        language=Language.FRENCH_CANADIAN,
        rag_assistant_system=_RAG_ASSISTANT_FR,
        answer_generator_system=_ANSWER_GEN_SYSTEM_FR,
        answer_prompt_builder=_build_answer_prompt_fr,
        hyde_system=_HYDE_SYSTEM_FR,
        reflection_system=_REFLECTION_SYSTEM_FR,
        followup_questions_template=_FOLLOWUP_FR,
        fallback_no_relevant_content=FALLBACK_NO_RELEVANT_CONTENT[Language.FRENCH_CANADIAN],
        fallback_limited_results=FALLBACK_LIMITED_RESULTS[Language.FRENCH_CANADIAN],
        answer_generation_error_template=ANSWER_GENERATION_ERROR[Language.FRENCH_CANADIAN],
        no_documents_fallback=NO_DOCUMENTS_FALLBACK[Language.FRENCH_CANADIAN],
        searched_without_filters_note=SEARCHED_WITHOUT_FILTERS_NOTE[Language.FRENCH_CANADIAN],
    ),
}


def get_prompts(language: "Language | str | None") -> LocalizedPrompts:
    """Return the ``LocalizedPrompts`` bundle for a given language (defaulting to English)."""
    return _PROMPTS[Language.from_value(language)]


@dataclass(frozen=True)
class IngestionPromptsBundle:
    """Skillset-side prompts grouped per language."""

    language: Language
    opco_extraction: str
    persona_extraction: str
    opco_normalization: str
    persona_normalization: str
    image_verbalization: str


_INGESTION: dict[Language, IngestionPromptsBundle] = {
    Language.ENGLISH: IngestionPromptsBundle(
        language=Language.ENGLISH,
        opco_extraction=IngestionPrompts.OPCO_EXTRACTION_SYSTEM_MESSAGE,
        persona_extraction=IngestionPrompts.PERSONA_EXTRACTION_SYSTEM_MESSAGE,
        opco_normalization=IngestionPrompts.OPCO_VALUE_NORMALIZATION_SYSTEM_MESSAGE,
        persona_normalization=IngestionPrompts.PERSONA_VALUE_NORMALIZATION_SYSTEM_MESSAGE,
        image_verbalization=IngestionPrompts.IMAGE_VERBALIZATION_SYSTEM_MESSAGE,
    ),
    Language.FRENCH_CANADIAN: IngestionPromptsBundle(
        language=Language.FRENCH_CANADIAN,
        opco_extraction=IngestionPromptsFR.OPCO_EXTRACTION_SYSTEM_MESSAGE,
        persona_extraction=IngestionPromptsFR.PERSONA_EXTRACTION_SYSTEM_MESSAGE,
        opco_normalization=IngestionPromptsFR.OPCO_VALUE_NORMALIZATION_SYSTEM_MESSAGE,
        persona_normalization=IngestionPromptsFR.PERSONA_VALUE_NORMALIZATION_SYSTEM_MESSAGE,
        image_verbalization=getattr(
            IngestionPromptsFR,
            "IMAGE_VERBALIZATION_SYSTEM_MESSAGE",
            IngestionPrompts.IMAGE_VERBALIZATION_SYSTEM_MESSAGE,
        ),
    ),
}


def get_ingestion_prompts(language: "Language | str | None") -> IngestionPromptsBundle:
    """Return the ingestion (skillset) prompt bundle for a given language."""
    return _INGESTION[Language.from_value(language)]


__all__ = [
    "LocalizedPrompts",
    "IngestionPromptsBundle",
    "IngestionPromptsFR",
    "get_prompts",
    "get_ingestion_prompts",
    "FALLBACK_NO_RELEVANT_CONTENT",
    "FALLBACK_LIMITED_RESULTS",
    "ANSWER_GENERATION_ERROR",
    "NO_DOCUMENTS_FALLBACK",
    "SEARCHED_WITHOUT_FILTERS_NOTE",
]
